# Generated by Django 4.2 on 2024-06-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagen',
            field=models.ImageField(blank=True, default='food/static/img/imageComing.jpeg', null=True, upload_to='food'),
        ),
    ]
