# Generated by Django 4.2 on 2024-07-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_dessertsitems_drinksitems_sidesitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessertsitems',
            name='product_type',
            field=models.CharField(default='desserts', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='drinksitems',
            name='product_type',
            field=models.CharField(default='drinks', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='product_type',
            field=models.CharField(default='itemx', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='sidesitems',
            name='product_type',
            field=models.CharField(default='sides', editable=False, max_length=200),
        ),
    ]
